### ISSUE TITLE
Drill acts like it's out of power after one use specifically on dedicated servers

### ISSUE THREAD

**Issue by sjl057** [MelnCat/ActuallySubtractions#14] opened 2024-11-28 03:33 UTC
I personally haven't tested this much as I'm not the server op for my friend group's server, but using the drill to break any block, regardless of its current CF causes it to act like it's out of power and refuse to break any more unless I shift it in my inventory, presumably refreshing its CF and making it think it's active again.

Even stranger, watching someone else use the drill shows the block almost breaking as if the server's reporting it is correctly breaking the block.

I tried to replicate this in a singleplayer world both with and without LAN active but couldn't, even with crafting/creativing in the same color drill.

This was happening on the latest released version, 1.2.14.7 running on NeoForge 1.20.1.
Our mod list is: https://hastebin.skyra.pw/oxururiniq.md

**Comment by MelnCat** [comment] 2024-11-28 05:18
Try with forge 1.20.1 instead. NeoForge is no longer supported for 1.20.1, and every 1.20.1 NeoForge mod works on forge anyways

**Comment by TheRoyalAdvisor** [comment] 2024-11-30 06:43
This still happens under Forge as well. Exactly as described.
Forge versions tested were 1.20.1-47.3.0 (the latest recommend version for 1.20.1) and 1.20.1-47.3.12 (the latest version for 1.20.1).

I also tested it with just Actually Subtractions and required dependencies, and this still occurs.

**Comment by MelnCat** [comment] 2024-11-30 08:12
I'll go test it out.

**Comment by Desenrrollado** [comment] 2024-12-15 06:07
I can confirm I also experience this in a dedicated server that I host on 1.20.1. It only works for one use, then I have to remove it from the offending slot to get another use. It's a shame since I really like this mod.

**Comment by MelnCat** [comment] 2024-12-27 07:13
Fixed in 1.2.14.8.

**Closed as completed by MelnCat** 2024-12-27 07:13 UTC
